### ISSUE TITLE
Custom location for Archives and Derived data

### ISSUE THREAD

**Issue by fvvliet** [vashpan/xcode-dev-cleaner#1]
Great tool, works like a charm !!!

It cannot handle custom locations for Derived data and Archives and find ~/Library/Developer at the same time. Any plans to support this ?

Cheers
Frank

**Comment by vashpan** [comment]
Good idea, although with sandbox it's a little bit tricky 😞 - normally it probably could even be read from Xcode preferences, but now access to each of those folders will have to be accepted by the user.

But I'll see what I can do 👍

**Comment by vashpan** [comment]
It was added in the latest version
