### ISSUE TITLE
Deleted files doesn't free the Disk space. Documents folder became larger after Cleaning up

### ISSUE THREAD

**Issue by pajtimid** [vashpan/xcode-dev-cleaner#10]
I Cleaned up my Xcode using the tool, but doesn't  work for me. I have same free space as was before, just Document folder became larger for that capacity that tool informs for deleting.

Xcode 10.3, macOS Mojave

**Comment by vashpan** [comment]
Please check it after a while. Since APFS, Finder is not reporting free space "live", also APFS itself is not working as straightforward. 

Also make sure you don't have "Dry Mode" enabled in Preferences.

If you'll still have ana issues, please submit next issue, or send me a message.
