### ISSUE TITLE
Feature request: Sorting by size inside the categories.

### ISSUE THREAD

**Issue by mladenny** [vashpan/xcode-dev-cleaner#12]
I thought of this recently, but I don’t have the skills to do it myself, otherwise I would’ve submitted another pull request 😬
As you can see in the screenshot, the projects in the Archives category aren’t ordered in a way that I can discern, so my suggestion is this: when you expand a category, maybe only Archives and Derived Data (up to you), the subitems to be sorted by size with the largest on top. That way you can quickly select the “worst offenders” to be deleted.
Whether you keep the sorting of the builds in each project in Archives like in my pull request, or decide those should also be ordered by descending size, is, again, up to you 😄

![Screenshot 2019-10-01 at 13 18 12](https://user-images.githubusercontent.com/9286345/65954211-36d4ab80-e44e-11e9-9547-60fbbfb96327.png)

**Comment by vashpan** [comment]
It will finally be a part of 2.4.0 release 😅

https://github.com/vashpan/xcode-dev-cleaner/commit/47a954761258f08be2b0e31d4c78a98fe2bd6629
