### ISSUE TITLE
Spacebar opens help instead of selecting checkboxes

### ISSUE THREAD

**Issue by igorkulman** [vashpan/xcode-dev-cleaner#13]
Say I want to select multiple old archives to be deleted, I use arrow key to navigate between them and press spacebar to select each of them. Instead of a checkbox being selected the help is opened:

![Dec-11-2019 12-07-29](https://user-images.githubusercontent.com/4746070/70616604-22abe800-1c0f-11ea-9951-012126798aaa.gif)

**Comment by vashpan** [comment]
Wow, this is weird, I’ll look at this soon 👍

**Comment by vashpan** [comment]
Hmm, I cannot reproduce it, is it happening always? Do you have some special keyboard or accessibility settings set?

**Comment by igorkulman** [comment]
Running Mojave, no special accessibility settings or anything like that, using a "standard" keyboard (Apple A1243).

Try this:
- open the Derived data section, or any section with more items
- click on any item in the list (not the checkbox but the item, so title or path) to select it
- press Up arrow
- press Space

**Comment by vashpan** [comment]
Hello, I checked it once again, on Mojave 10.4.6 VM - and as before - cannot reproduce it, trying to  do exact steps as described.

If there's someone else with this issue, I would welcome more info about it!

**Comment by vashpan** [comment]
Cannot reproduce, if someone will be able to do it, I'll reopen.
