### ISSUE TITLE
Xcode's cache might take lots of room

### ISSUE THREAD

**Issue by acalism** [vashpan/xcode-dev-cleaner#14]
My `~/Library/Caches/com.apple.dt.Xcode/Downloads` takes more than 10G.
`/Library/Developer/CoreSimulator/Profiles/Runtimes` takes too much disk space.
Could you add these folders to your DevClean App's project?

**Comment by vashpan** [comment]
Stuff in "~/Library/Caches" should be cleaned by OS from time to time, these are probably some unfinished downloads, as I don't have Xcode folder there at all...

`/Library/Developer/CoreSimulator/Profiles/Runtimes` - unfortunately, this folder is on root volume, and root access is required to get it. It also requires running `xcrun simctl delete unavailable` after removing runtimes there. Both thing are unfortunately unavailable to apps running from sandbox.

I'll be checking more things to cleanly remove though
