### ISSUE TITLE
Feature request: cleaning simulator runtimes

### ISSUE THREAD

**Issue by igorkulman** [vashpan/xcode-dev-cleaner#15]
If you download a simulator runtime via Xcode, there is no easy way to delete it. You have to manually delete it from `~/Library/Developer/Xcode/iOS DeviceSupport`, so the app can offer that option.

**Comment by vashpan** [comment]
`iOS DeviceSupport` is actually used for iOS symbols copied from devices - and those folders are handled by DevCleaner. 

Simulator runtimes are stored elsewhere - unfortunately they're shared in system `/Library` folder, hence DevCleaner can't access them (or at least it's problematic)

I'm looking into other places though, also related to simulators!

**Comment by igorkulman** [comment]
I copy pasted wrong path, sorry, I  meant /Library/Developer/CoreSimulator/Profiles/Runtimes
