### ISSUE TITLE
Feature request: Delete EmbeddedAppDeltas content

### ISSUE THREAD

**Issue by ffittschen** [vashpan/xcode-dev-cleaner#16]
I recently discovered that there is a folder located a `/private/var/folders/m2/.../C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas` which contains a lot of old builds (or deltas?) which don't seem to be cleaned by the OS in any way. For me they date back to the day I got my MacBook. It would be great if this folder could be listed in DevCleaner as well.

**Comment by vashpan** [comment]
I think that `/private/var` folders are temporary and cached, and should be cleaned up by OS. I usually don't want to interfere in that, because who knows how it's used.

I'll monitor that though because indeed I also have some old stuff there. Maybe OS is cleaning them only if needed? Who knows.
