### ISSUE TITLE
Archive list incomplete

### ISSUE THREAD

**Issue by SeNeO** [vashpan/xcode-dev-cleaner#17]
The list contain only certain archives whom version number respect X.X.X.
I often use someting like X.X.X.alpha-1 or X.X.X.beta-2 and this archives are not listed. Is there anyway to have them listed?

**Comment by vashpan** [comment]
Thanks for that! Indeed it may be the issue with such versions

**Comment by vashpan** [comment]
Should be fixed in 2.3.0, fixed in https://github.com/vashpan/xcode-dev-cleaner/commit/0ec230a62323c991d5c146fa2094fd3fc8d1d646

**Comment by SeNeO** [comment]
Indeed it works. Thank you.
