### ISSUE TITLE
Adding DevCleaner to Homebrew

### ISSUE THREAD

**Issue by mateuszjablonski** [vashpan/xcode-dev-cleaner#18]
Would you consider adding DevCleaner to Homebrew Cask? I would assume there are plenty of developers who use Homebrew as their main any only source of apps.

**Comment by vashpan** [comment]
I may consider that - although it would require some (small) work on non-MAS version. In the long-run, having DevCleaner outside Mac App Store may be much more beneficial and allow for much more features that are currently limited by sandbox and/or Apple review guidelines.

In the meantime, it seems that there is a command line interface to MAS: https://github.com/mas-cli/mas

**Comment by martin-braun** [comment]
Hi @vashpan, I love your DevCleaner, great work. However I decided not to use the App Store from Apple, heck I'm not even signed into my iCloud account in the system preferences. Luckily I can sign in within Xcode to distribute apps without signing in on my MacBook system-wide, but I cannot sign-in to the App Store without signing in system-wide.

I'd really love to see your DevCleaner on Homebrew.

**Comment by mateuszjablonski** [comment]
Since the build is publicly available, I created a cask PR to Homebrew repository: https://github.com/Homebrew/homebrew-cask/pull/131493

**Comment by mateuszjablonski** [comment]
@martin-braun @johnrm9 DevCleaner is now accessible via Homebrew
```
% brew info devcleaner
==> devcleaner: 2.3.1-425
https://github.com/vashpan/xcode-dev-cleaner
/usr/local/Caskroom/devcleaner/2.3.1 (124B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/devcleaner.rb
==> Name
DevCleaner
==> Description
Reclaim tens of gigabytes of your storage used for various Xcode caches
==> Artifacts
DevCleaner.app (App)
==> Analytics
install: 3 (30 days), 3 (90 days), 3 (365 days)
mateuszjablonski@MacBook-Pro-Mateusz mapa-apostazji-pl % 
```

**Comment by martin-braun** [comment]
@mateuszjablonski I really appreciate your contribution. It works like charm, thank you. 😀

**Comment by vashpan** [comment]
Thanks for your effort @mateuszjablonski 🙂
