### ISSUE TITLE
where is the command line tool?

### ISSUE THREAD

**Issue by jjcaballero** [vashpan/xcode-dev-cleaner#19]
I would like to use the command-line tool of DevCleaner. Where can I find it? Also, if there is some kind of instructions/documentation that would be great.

Is there any recommended way to schedule some periodic cleaning process?

Thanks!

**Comment by vashpan** [comment]
Here are the instructions how to install command line tool for DevCleaner: https://github.com/vashpan/xcode-dev-cleaner/blob/2.0.0/Documentation/Command%20Line%20Tool.md
