### ISSUE TITLE
Show empty "Device Support"

### ISSUE THREAD

**Issue by mrvincenzo** [vashpan/xcode-dev-cleaner#25]
Archives, Derived Data & all the other are shown correctly. What can be the reason?

Is tehre any way to "reset" the app and force it to show the developer directory selection again?

**Comment by mrvincenzo** [comment]
My bad. It is just empty. For some reason, I though the app looks for stuff in
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport`.

BTW, what about the above - can some old stuff OS version be deleted from there?

**Comment by vashpan** [comment]
> BTW, what about the above - can some old stuff OS version be deleted from there?

No, this is iOS platform SDK and definitely shouldn't be touched, as everything that is inside Xcode app bundle 😉
