### ISSUE TITLE
Sort Device Support versions and builds chronologically

### ISSUE THREAD

**Issue by orthohedron** [vashpan/xcode-dev-cleaner#28]
When the app lists multiple builds of multiple versions of Device Support, it sorts the versions by newest first, but within each version, it sorts the builds by oldest first.

It would be easier to identify old builds if the list were chronological overall. The latest build of the latest version should be on the top or the bottom.

<img width="772" alt="Screenshot" src="https://user-images.githubusercontent.com/83936063/126046201-6b99c4df-9776-498e-a2f0-9e106a8a9190.png">

**Comment by vashpan** [comment]
Thanks for that idea 👍 I rarely have a lot of betas installed so maybe didn't noticed that as an issue. It definitely should be sorted with a build number (id?) as well.

No to figure out what's the Apple convention for them? 😀 I don't think those are hex numbers, rather some kind of id? 🤔 

Anyone knows? Maybe someone from Apple?

**Comment by vashpan** [comment]
I found some informations about this: https://tidbits.com/2020/07/08/how-to-decode-apple-version-and-build-numbers/ and implemented in the next version of DevCleaner 🙂 Should now sort them much more sensible, although for some edge cases it may need some fix in the future. Check this commit: e4b376b
