### ISSUE TITLE
Add dry-run flag to dev-cleaner command line

### ISSUE THREAD

**Issue by johnrm9** [vashpan/xcode-dev-cleaner#30]
Would you add dry-run flag to dev-cleaner command line?

**Comment by vashpan** [comment]
Any specific reason why to include this? 🤔 Command line tool already has `dev-cleaner info` command that shows what things are to clean. 

Command line tool doesn't support to select specific things to clean, so usefulness is rather limited... 🤔

**Comment by johnrm9** [comment]
There are the commands: dev-cleaner clean archives and dev-cleaner clean derived-data.
Would adding a --dry-run flag be helpful in those cases? Also, the command dev-cleaner clean all.

**Comment by vashpan** [comment]
I would close it, as I still can't see any specific scenario when it could be useful 🤔
