### ISSUE TITLE
Tip: Developer/CoreSimulator/Caches - disable AutomaticallyGenerateDyldShareCache

### ISSUE THREAD

**Issue by Volodymyr-13** [vashpan/xcode-dev-cleaner#33]
Size of my folder: _/Users/user/Library/Developer/CoreSimulator/Caches_ is **~5,08 Gb**. I'm not using Simulators at all, never launched any. After every Xcode update this folder re-appears and every time I remove it manually.. 

**Found a solution:** 
Prevent automatic CPU-heavy generation of multi-gigabyte files in  _/Users/user/Library/Developer/CoreSimulator/Caches_

`defaults write com.apple.CoreSimulator AutomaticallyGenerateDyldShareCache 0`

But might impact its performance. Tested on Xcode 12 and 13.

Perhaps such an option can be given as a tip to users right inside of this app.

**Comment by vashpan** [comment]
It's a great tip definitely 👍, but I don't think it should be a part of DevCleaner. 

Cleaning those caches might be an option and I thought about it, but decided to avoid clearing caches that Xcode properly handles itself (for example: deletes older after update, generates them every time you start Xcode or Simulator) - they genuinely helps in performance and DevCleaner tries to be relatively conservative on that regard.
