### ISSUE TITLE
What about Previews?

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [vashpan/xcode-dev-cleaner#46]
Hi,

I just used DevCleaner and realized that it doesn't pick up the Previews directory on `/Users/isuru/Library/Developer/Xcode/UserData/` location. I don't know if my memory is hazy but I think I remember DevCleaner used to show this directory in the list as well.

Was it removed for some reason? Or am I just talking crazy? 😅

**Comment by vashpan** [comment]
Yes, it did supported it. But unfortunately it was buggy and also broken. At some point Apple changed something with permissions related to previews and DevCleaner couldn't really delete them anyway. I'm monitoring the issue though and maybe in the future I'll find a way.
