### ISSUE TITLE
Not working with Xcode 16

### ISSUE THREAD

**Issue by catach** [vashpan/xcode-dev-cleaner#49]
<img width="608" alt="Screenshot 2024-09-18 at 2 34 05 PM" src="https://github.com/user-attachments/assets/9a028a79-c095-44ed-bb0e-60fe8d24915e">

It couldn't find the older sims

**Comment by vashpan** [comment]
This is about old logs - newer Xcodes doesn't support it, I might change the name as it indeed might be confusing 🤔

**Comment by catach** [comment]
Hey @vashpan I was asking about the "Device Support" checkbox. I'm running Xocde 16 with iOS 18 and iOS 17.5 sims, but DevCleaner can't find the 17.5. That used to work in the past. I tested your new version 2.7.0 and it still can't find the older sims... Maybe I'm missing something, though. Thanks for your work on this :)

**Comment by vashpan** [comment]
Device support section is about symbols that Xcode download from devices you connect into it - those are not simulators nor their runtimes.

From DevCleaner help:

> In order to debug iOS/tvOS/iPadOS/watchOS/macOS devices, Xcode first needs to download debug symbols appropriate to version of OS that we currently use on a device. You may noticed that when connecting a new or updated device when having Xcode opened.
> 
> Those symbols are needed for each of your device and for each of *OS version, after a new update, even a minor one, Xcode needs a new set of symbols. Unfortunately, old symbols are not removed and each of them take 2-5GB of disk space. As you can imagine, they can start to sum up pretty quickly, usually there's 10s of smaller updates in less than a year for each OS.
> 
> DevCleaner helps cleaning those symbols, selecting older ones by default, keeping only those most recent ones. Of course final decision is yours.
