### ISSUE TITLE
build error: Your development team, does not support the In-App Purchase capability.

### ISSUE THREAD

**Issue by arielelkin** [vashpan/xcode-dev-cleaner#6]
Fresh clone from master on Xcode 10.3, hit run, I get a provisioning profile build error, switch to my development team, and i get the build error in this github issue's title. 

Why do i need a dev team with in-app purchase capabilities to run this?

**Comment by vashpan** [comment]
Because this is now project is made, you can disable IAP capabilities, and remove IAP code. 

Also you can just download it from Mac App Store if you just want to use it: https://apps.apple.com/pl/app/devcleaner-for-xcode/id1388020431?l=pl&mt=12
