### ISSUE TITLE
Feature Request: Allow easier multi selection

### ISSUE THREAD

**Issue by funkenstrahlen** [vashpan/xcode-dev-cleaner#7]
I quite often need to clean numerous builds of an app but not all of them.

Right now I have to manually select all the checkboxes for each build. I would love to be able to select multiple builds at once / faster.

Most intuitive behavior in my eyes:
* Select one build
* Shift-Click another build to select all builds in between
* Clicking the checkbox of one selected build checks all checkboxes of selected builds

**Comment by vashpan** [comment]
I think it will be a bit overcomplicated. Currently it's possible to select items with Spacebar, which is quicker than mouse, but I just found a bug in this 😀

**Comment by funkenstrahlen** [comment]
If you can fix selecting with spacebar and arrows I am happy 😃
