### ISSUE TITLE
In App Purchase broken

### ISSUE THREAD

**Issue by funkenstrahlen** [vashpan/xcode-dev-cleaner#8]
This error occurs when I try to buy a tip in app purchase:

<img width="424" alt="Screen Shot 2019-09-09 at 13 41 12" src="https://user-images.githubusercontent.com/144173/64527926-802a5300-d307-11e9-86e5-53f951418314.png">

Version `1.1.3`

**Comment by vashpan** [comment]
I think this is related to Mac enterprise deployment, probably your machine is managed by your company. https://community.meraki.com/t5/Dashboard-Administration/In-App-purchase-is-not-supported-machine-licensed-app-does-not/td-p/51567

If possible, consider downloading to your private machine and buy IAP then.

**Comment by funkenstrahlen** [comment]
I am using this on my own MacBook Pro. There are no enterprise restrictions applied.

I will try to reinstall the app later today. Maybe this is going to help.

**Comment by vashpan** [comment]
Hmm, so that's super weird. So you use your own private AppStore account that works for other apps? 

It's clearly a message from OS/AppStore, AFAIK I do everything "by the book" in terms of IAP support. 

I would be grateful if you would let me know if reinstall worked.

**Comment by funkenstrahlen** [comment]
I just reinstalled DevCleaner from the App Store. I could purchase the IAP without any issues now. Enjoy your coffee! :)

**Comment by vashpan** [comment]
Thanks 👍😀

Probably some store glitch, I'm glad it's working fine!
